<?php

// 0          10         20         30         40         50         60         70         80         90
// SDHFAOJSOD IFJOPAISJD FIHDIJFLKJ SDBFJHBVLA JBDVLJANPA NMANLJADSB FJHBASJHDB VJAHBSDJKV HBASJKHDBV JKHABSDJHV
// BASJHBDVJS AHBDVJKHAS BDVKJHSBDJ VKHBSKJAHD BVJSHBDVAN PANMANASJH DBFJKASHBD FJKAHBSDKF JHABSANPAN MANSADASDF
// ASDFASDFAS DFAS
//
// occurrences: 47, 149, 186

require_once('interfaces/StringSearchable.php');
require_once('classes/Search/String/BoyerMoore.php');

$bm = new BoyerMoore();

// search for 'substring' in 'buffer'
$bm->search('ANPANMAN', 'SDHFAOJSODIFJOPAISJDFIHDIJFLKJSDBFJHBVLA'
				. 'JBDVLJANPANMANLJADSBFJHBASJHDBVJAHBSDJKVHBASJKHDBVJ'
				. 'KHABSDJHVBASJHBDVJSAHBDVJKHASBDVKJHSBDJVKHBSKJAHDBV'
				. 'JSHBDVANPANMANASJHDBFJKASHBDFJKAHBSDKFJHABSANPANMAN'
				. 'SADASDFASDFASDFASDFAS');

// output results
var_dump($bm->getResults());

?>